# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dariusgiannoli/Desktop/Final/data/event_metadata.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventMetadataWidget(object):
    def setupUi(self, EventMetadataWidget):
        EventMetadataWidget.setObjectName("EventMetadataWidget")
        EventMetadataWidget.resize(400, 300)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(EventMetadataWidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.name_layout = QtWidgets.QHBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.name_label = QtWidgets.QLabel(EventMetadataWidget)
        self.name_label.setObjectName("name_label")
        self.name_layout.addWidget(self.name_label)
        self.name_edit = QtWidgets.QLineEdit(EventMetadataWidget)
        self.name_edit.setObjectName("name_edit")
        self.name_layout.addWidget(self.name_edit)
        self.verticalLayout_main.addLayout(self.name_layout)
        self.category_layout = QtWidgets.QHBoxLayout()
        self.category_layout.setObjectName("category_layout")
        self.category_label = QtWidgets.QLabel(EventMetadataWidget)
        self.category_label.setObjectName("category_label")
        self.category_layout.addWidget(self.category_label)
        self.category_combo = QtWidgets.QComboBox(EventMetadataWidget)
        self.category_combo.setObjectName("category_combo")
        self.category_layout.addWidget(self.category_combo)
        self.verticalLayout_main.addLayout(self.category_layout)
        self.description_label = QtWidgets.QLabel(EventMetadataWidget)
        self.description_label.setObjectName("description_label")
        self.verticalLayout_main.addWidget(self.description_label)
        self.description_edit = QtWidgets.QTextEdit(EventMetadataWidget)
        self.description_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.description_edit.setObjectName("description_edit")
        self.verticalLayout_main.addWidget(self.description_edit)
        self.tags_layout = QtWidgets.QHBoxLayout()
        self.tags_layout.setObjectName("tags_layout")
        self.tags_label = QtWidgets.QLabel(EventMetadataWidget)
        self.tags_label.setObjectName("tags_label")
        self.tags_layout.addWidget(self.tags_label)
        self.tags_edit = QtWidgets.QLineEdit(EventMetadataWidget)
        self.tags_edit.setObjectName("tags_edit")
        self.tags_layout.addWidget(self.tags_edit)
        self.verticalLayout_main.addLayout(self.tags_layout)
        self.author_layout = QtWidgets.QHBoxLayout()
        self.author_layout.setObjectName("author_layout")
        self.author_label = QtWidgets.QLabel(EventMetadataWidget)
        self.author_label.setObjectName("author_label")
        self.author_layout.addWidget(self.author_label)
        self.author_edit = QtWidgets.QLineEdit(EventMetadataWidget)
        self.author_edit.setObjectName("author_edit")
        self.author_layout.addWidget(self.author_edit)
        self.verticalLayout_main.addLayout(self.author_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem)

        self.retranslateUi(EventMetadataWidget)
        QtCore.QMetaObject.connectSlotsByName(EventMetadataWidget)

    def retranslateUi(self, EventMetadataWidget):
        _translate = QtCore.QCoreApplication.translate
        EventMetadataWidget.setWindowTitle(_translate("EventMetadataWidget", "Event Metadata"))
        self.name_label.setText(_translate("EventMetadataWidget", "Event Name:"))
        self.category_label.setText(_translate("EventMetadataWidget", "Category:"))
        self.description_label.setText(_translate("EventMetadataWidget", "Description:"))
        self.tags_label.setText(_translate("EventMetadataWidget", "Tags:"))
        self.tags_edit.setPlaceholderText(_translate("EventMetadataWidget", "tag1, tag2, tag3"))
        self.author_label.setText(_translate("EventMetadataWidget", "Author:"))
